name: "Android 12 - Kernel 5.10"

permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      ksu_variant:
        type: string
        default: "KernelSU-Next"
      add_susfs:
        type: boolean
        default: true
      add_enhanced_susfs:
        type: boolean
        default: true
      add_unicode_filter:
        type: boolean
        default: true
      add_zeromount:
        type: boolean
        default: true
      add_zram:
        type: boolean
        default: true
      add_bbg:
        type: boolean
        default: true
      add_kpm:
        type: boolean
        default: false

jobs:
  download-dependencies:
    uses: ./.github/workflows/cache-dependencies.yml
    permissions:
      contents: read
      actions: write

  build:
    needs: [download-dependencies]
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "107"
            os_patch_level: "2022-03"
          - sub_level: "107"
            os_patch_level: "2022-05"
          - sub_level: "107"
            os_patch_level: "2022-07"
          - sub_level: "107"
            os_patch_level: "2022-09"
          - sub_level: "107"
            os_patch_level: "2022-11"
          - sub_level: "149"
            os_patch_level: "2023-01"
          - sub_level: "157"
            os_patch_level: "2023-03"
          - sub_level: "168"
            os_patch_level: "2023-05"
          - sub_level: "177"
            os_patch_level: "2023-07"
          - sub_level: "186"
            os_patch_level: "2023-09"
          - sub_level: "189"
            os_patch_level: "2023-11"
          - sub_level: "198"
            os_patch_level: "2024-01"
          - sub_level: "205"
            os_patch_level: "2024-03"
          - sub_level: "209"
            os_patch_level: "2024-05"
          - sub_level: "218"
            os_patch_level: "2024-08"
          - sub_level: "226"
            os_patch_level: "2024-11"
          - sub_level: "233"
            os_patch_level: "2025-02"
          - sub_level: "236"
            os_patch_level: "2025-05"
          - sub_level: "237"
            os_patch_level: "2025-06"
          - sub_level: "240"
            os_patch_level: "2025-09"
          - sub_level: "246"
            os_patch_level: "2025-12"
    uses: ./.github/workflows/gki-build.yml
    with:
      android_version: android12
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_variant: ${{ inputs.ksu_variant }}
      add_susfs: ${{ inputs.add_susfs }}
      add_enhanced_susfs: ${{ inputs.add_enhanced_susfs }}
      add_unicode_filter: ${{ inputs.add_unicode_filter }}
      add_zeromount: ${{ inputs.add_zeromount }}
      add_zram: ${{ inputs.add_zram }}
      add_bbg: ${{ inputs.add_bbg }}
      add_kpm: ${{ inputs.add_kpm }}
      device_codename: "generic"
